# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml
stages:
  - build
  - test

image: dostapazov/msvc-2019

build-x32:
  stage: build

  script:
    - msbuild -p:Configuration=Debug -p:Platform=Win32
  artifacts:
    paths:
      - Debug
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

build-x64:
  stage: build

  script:
    - msbuild -p:Configuration=Debug -p:Platform=x64
  artifacts:
    paths:
      - x64/Debug

test-api-x32:
  stage: test
  script:
    - Debug/ApiTest.exe
  dependencies:
    - build-x32

test-api-x64:
  stage: test
  script:
    - x64/Debug/ApiTest.exe
  dependencies:
    - build-x64
